export let mydata={
    id:"1",
    name:'myFile',
    isFolder:true,
    items:[
        {
            id:"2",
            name:"public",
            isFolder:true,
            items:[
                {
                    id:"3",
                    name:"index.html",
                    isFolder:false,
                    items:[]
                },
                {
                  id:"4",
                  name:"manifest.json",
                  isFolder:false,
                  items:[]
                }
            ]
        },
        {
            id:"3",
            name:"src",
            isFolder:true,
            items:[]
        },
        {
            id:"4",
            name:"App.css",
            isFolder:false,
            items:[]
        },
        {
            id:"5",
            name:"Appp.test.js",
            isFolder:false,
            items:[]
        },
        {
            id:"6",
            name:"index.css",
            isFolder:false,
            items:[]
        }
    ]
    
}